# Generated by Django 5.2.7 on 2025-11-18 01:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity_in_stock', models.IntegerField(default=0)),
                ('quantity_sold', models.IntegerField(default=0)),
                ('min_stock_level', models.IntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='shops.shop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StockHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_before', models.IntegerField()),
                ('quantity_after', models.IntegerField()),
                ('action', models.CharField(choices=[('sold', 'Sold'), ('added', 'Added'), ('adjusted', 'Adjusted')], max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='inventory.stock')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['shop', 'user'], name='inventory_s_shop_id_4d56c4_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['created_at'], name='inventory_s_created_913bee_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['shop', 'created_at'], name='inventory_s_shop_id_5c3113_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('shop', 'name')},
        ),
        migrations.AddIndex(
            model_name='stockhistory',
            index=models.Index(fields=['stock', 'created_at'], name='inventory_s_stock_i_5ad8fc_idx'),
        ),
    ]
